name       : milkytracker
version    : 1.02.00
release    : 4
source     :
    - https://github.com/milkytracker/MilkyTracker/archive/v1.02.00.tar.gz : 6bcb6e74ee333e831137435a25c0f2f3da6e1462864deec9e693ef7d23a16023
license    : GPL-3.0-only
component  : multimedia.audio
summary    : An FT2 compatible music tracker.
description: |
    An FT2 compatible music tracker.
builddeps  :
    - pkgconfig(jack)
    - pkgconfig(rtmidi)
    - pkgconfig(sdl2)
    - alsa-tools
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $workdir/resources/milkytracker.desktop $installdir/usr/share/applications/milkytracker.desktop
    install -Dm00644 $pkgfiles/milkytracker.png $installdir/usr/share/pixmaps/milkytracker.png
