name       : milkytracker
version    : 1.04.00
release    : 10
source     :
    - https://github.com/milkytracker/MilkyTracker/archive/refs/tags/v1.04.00.tar.gz : a0bfabcec5bdb64c83c1e08cd12d979fefc53fc41cafd07c67b640bd5ba0ec67
homepage   : https://milkytracker.org/
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : An FT2 compatible music tracker
description: |
    MilkyTracker is an multi-platform music application for creating .MOD and .XM module files. It attempts to recreate the module replay and user experience of the popular DOS program Fasttracker II, with special playback modes available for improved Amiga ProTracker 2/3 compatibility.
builddeps  :
    - pkgconfig(jack)
    - pkgconfig(rtmidi)
    - pkgconfig(sdl2)
    - alsa-tools
setup      : |
    %patch -p1 < $pkgfiles/fix-crash.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 resources/pictures/carton.png $installdir/usr/share/pixmaps/milkytracker.png
    install -Dm00644 resources/milkytracker.desktop $installdir/usr/share/applications/milkytracker.desktop
    install -Dm00644 resources/milkytracker.appdata $installdir/usr/share/appdata/milkytracker.appdata.xml
    rm -r $installdir/usr/share/doc
